version: "3.9"

services:
  bitcoind:
    image: ${BITCOIND_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-bitcoind
    command:
      -printtoconsole=1
      -regtest=1
      -server=1
      -txindex=1
      -fallbackfee=0.0002
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcport=18443
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
    ports:
      - "${BITCOIN_RPC_PORT}:18443"
      - "${BITCOIN_P2P_PORT}:18444"
      - "${BITCOIN_ZMQ_BLOCK}:28332"
      - "${BITCOIN_ZMQ_TX}:28333"
    volumes:
      - ./data/bitcoind:/home/bitcoin/.bitcoin
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=bitcoin", "-rpcpassword=bitcoin", "getblockchaininfo"]
      interval: 5s
      timeout: 3s
      retries: 30

  lnd-alice:
    image: ${LND_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-lnd-alice
    depends_on:
      bitcoind:
        condition: service_healthy
    command:
      - --bitcoin.active
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:18443
      - --bitcoind.rpcuser=bitcoin
      - --bitcoind.rpcpass=bitcoin
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --rpclisten=0.0.0.0:10009
      - --restlisten=0.0.0.0:8080
      - --listen=0.0.0.0:9735
      - --alias=alice
      - --color=#33cc99
    ports:
      - "${ALICE_GRPC}:10009"
      - "${ALICE_REST}:8080"
      - "${ALICE_P2P}:9735"
    volumes:
      - ./lnd/lnd-alice.conf:/root/.lnd/lnd.conf:ro
      - ./data/lnd-alice:/root/.lnd

  lnd-bob:
    image: ${LND_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-lnd-bob
    depends_on:
      bitcoind:
        condition: service_healthy
    command:
      - --bitcoin.active
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind:18443
      - --bitcoind.rpcuser=bitcoin
      - --bitcoind.rpcpass=bitcoin
      - --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      - --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      - --rpclisten=0.0.0.0:10009
      - --restlisten=0.0.0.0:8080
      - --listen=0.0.0.0:9735
      - --alias=bob
      - --color=#3366ff
    ports:
      - "${BOB_GRPC}:10009"
      - "${BOB_REST}:8080"
      - "${BOB_P2P}:9735"
    volumes:
      - ./lnd/lnd-bob.conf:/root/.lnd/lnd.conf:ro
      - ./data/lnd-bob:/root/.lnd

networks:
  default:
    name: ${DOCKER_NETWORK}
