name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: >-
      Lightnex Test (Elixir ${{ matrix.elixir }} /
      OTP ${{ matrix.otp }} /
      OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - elixir: 1.18.x
            otp: 28.x
            os: 'ubuntu-latest'
            lint: true
            coverage: true
            integration: true
            sobelow: true
            dialyzer: true
          - elixir: 1.17.x
            otp: 27.x
            os: 'ubuntu-latest'
          - elixir: 1.17.x
            otp: 25.x
            os: 'ubuntu-latest'

    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Start Docker with CI user permissions
        run: |
          # Export UID and GID for docker-compose
          export UID=$(id -u)
          export GID=$(id -g)
          echo "Starting Docker as UID=$UID GID=$GID"

          # Create data directories with correct ownership
          mkdir -p docker/data/lnd-alice docker/data/lnd-bob docker/data/bitcoind

          # Start docker with user override
          docker compose -f docker/docker-compose.yml up --detach --wait
        env:
          UID: ${{ env.UID }}
          GID: ${{ env.GID }}
        if: ${{ matrix.integration }}

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '${{ matrix.otp }}'
          elixir-version: '${{ matrix.elixir }}'

      - name: Cache deps
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: >-
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-

      - name: Cache _build
        uses: actions/cache@v3
        with:
          path: _build
          key: >-
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
        if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}

      - name: Compile deps
        run: mix deps.compile

      - name: Check unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Compile lint
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run style and code consistency checks
        run: |
          mix format --check-formatted
          mix credo --strict
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test --exclude integration
        if: ${{ !matrix.coverage && !matrix.integration }}

      - name: Run tests with coverage
        run: mix coveralls.json --exclude integration
        if: ${{ matrix.coverage }}

      - name: Run integration tests
        run: mix test --only integration
        if: ${{ matrix.integration }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          flags: unittests-elixir-${{ matrix.elixir }}-otp-${{ matrix.otp }}
        if: ${{ matrix.coverage }}

      - name: Run sobelow
        run: mix sobelow -i Traversal.FileModule --skip --exit Low
        if: ${{ matrix.sobelow }}

      - name: Restore PLT Cache
        uses: actions/cache@v3
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt-v1
        if: ${{ matrix.dialyzer }}

      - name: Create PLTs
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
        if: ${{ matrix.dialyzer && steps.plt-cache.outputs.cache-hit != 'true' }}

      - name: Run dialyzer
        run: mix dialyzer --format github
        if: ${{ matrix.dialyzer && steps.plt-cache.outputs.cache-hit != 'true' }}
